version: '1.0'
content_version: 1.0.0
description: Security audit snapshot (roles and teams) captured from https://crm-test.clevelandbusinessmentors.org/ on 2026-06-25T06:30:25Z.
teams:
- name: Client Administration Team
- name: Data Integrity Team
- name: Mentor Administration Team
  description: 'This is the team that is responsible for reviewing new Mentor Applications,  monitoring mentor performance,
    and managing mentor retirement.

    They have administrative permissions to change any Mentor, Engagement, or Client records.'
- name: Mentor Team
- name: Partner Management Team
- name: Sponsor Management Team
- name: System Administration Team
roles:
- name: Client Assignment Role
  scope_access:
    Email:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: 'no'
    Account:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Contact:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Document:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: 'no'
    KnowledgeBaseArticle:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: 'no'
    Report:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: 'no'
    MentorProfile:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    ClientProfile:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Engagement:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    IntakeSubmission:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Session:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
  system_permissions:
    assignment_permission: all
    user_permission: not-set
    export: false
    mass_update: false
    portal: false
- name: ClientMentorIntakeRole
  scope_access:
    Account:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Contact:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    MentorProfile:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    ClientProfile:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Engagement:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Event:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    InformationRequest:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: 'no'
    IntakeSubmission:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    PartnerProfile:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    SponsorProfile:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
  system_permissions:
    assignment_permission: all
    user_permission: not-set
    export: false
    mass_update: false
    portal: false
- name: ContentAndEventAdmin
  scope_access:
    Event:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: 'no'
  system_permissions:
    assignment_permission: not-set
    user_permission: not-set
    export: false
    mass_update: false
    portal: false
- name: Data Integrity Team Role
  system_permissions:
    assignment_permission: not-set
    user_permission: not-set
    export: false
    mass_update: false
    portal: false
- name: Event Manager Role
  system_permissions:
    assignment_permission: not-set
    user_permission: not-set
    export: false
    mass_update: false
    portal: false
- name: Mentor Administration Role
  scope_access:
    Team:
      create: false
      read: all
      edit: 'no'
      delete: 'no'
      stream: 'no'
    User:
      create: false
      read: all
      edit: own
      delete: 'no'
      stream: 'no'
    Account:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Contact:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Report:
      create: true
      read: team
      edit: team
      delete: 'no'
      stream: 'no'
    MentorProfile:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    ClientProfile:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Engagement:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    IntakeSubmission:
      create: false
      read: all
      edit: all
      delete: 'no'
      stream: all
    Session:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
  system_permissions:
    assignment_permission: all
    user_permission: not-set
    export: false
    mass_update: true
    portal: false
- name: Mentor Role
  scope_access:
    EmailTemplate:
      create: true
      read: team
      edit: team
      delete: own
      stream: 'no'
    Email:
      create: true
      read: own
      edit: own
      delete: own
      stream: 'no'
    User:
      create: false
      read: team
      edit: own
      delete: 'no'
      stream: 'no'
    Account:
      create: true
      read: all
      edit: own
      delete: 'no'
      stream: own
    Contact:
      create: true
      read: all
      edit: own
      delete: 'no'
      stream: own
    ReportCategory:
      create: false
      read: team
      edit: 'no'
      delete: 'no'
      stream: 'no'
    Report:
      create: true
      read: team
      edit: own
      delete: own
      stream: 'no'
    MentorProfile:
      create: false
      read: all
      edit: all
      delete: 'no'
      stream: 'no'
    ClientProfile:
      create: false
      read: own
      edit: own
      delete: 'no'
      stream: own
    Engagement:
      create: false
      read: own
      edit: own
      delete: 'no'
      stream: own
    Event:
      create: false
      read: all
      edit: own
      delete: 'no'
      stream: own
    Session:
      create: true
      read: own
      edit: own
      delete: 'no'
      stream: own
  system_permissions:
    assignment_permission: team
    user_permission: not-set
    export: false
    mass_update: false
    portal: false
- name: Partner Manager Role
  scope_access:
    Account:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: team
    Contact:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: team
    Report:
      create: true
      read: all
      edit: team
      delete: 'no'
      stream: 'no'
    MentorProfile:
      create: true
      read: all
      edit: team
      delete: 'no'
      stream: all
    ClientProfile:
      create: true
      read: all
      edit: team
      delete: 'no'
      stream: all
    PartnerProfile:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: all
    Session:
      create: true
      read: all
      edit: team
      delete: 'no'
      stream: all
    SponsorProfile:
      create: true
      read: all
      edit: team
      delete: 'no'
      stream: all
  system_permissions:
    assignment_permission: all
    user_permission: not-set
    export: false
    mass_update: false
    portal: false
- name: Sponsor Manager Role
  scope_access:
    Account:
      create: true
      read: team
      edit: team
      delete: 'no'
      stream: team
    Contact:
      create: true
      read: team
      edit: team
      delete: 'no'
      stream: team
    SponsorProfile:
      create: true
      read: team
      edit: team
      delete: 'no'
      stream: 'no'
  system_permissions:
    assignment_permission: not-set
    user_permission: not-set
    export: false
    mass_update: false
    portal: false
- name: Standard User
  scope_access:
    EmailTemplateCategory:
      create: false
      read: all
      edit: 'no'
      delete: 'no'
      stream: 'no'
    EmailTemplate:
      create: true
      read: all
      edit: 'no'
      delete: 'no'
      stream: 'no'
    Email:
      create: true
      read: all
      edit: all
      delete: 'no'
      stream: 'no'
    Engagement:
      create: true
      read: own
      edit: own
      delete: 'no'
      stream: 'no'
    Event:
      create: true
      read: own
      edit: own
      delete: 'no'
      stream: 'no'
    MentorProfile:
      create: false
      read: all
      edit: 'no'
      delete: 'no'
      stream: 'no'
    Session:
      create: true
      read: own
      edit: own
      delete: 'no'
      stream: 'no'
  system_permissions:
    assignment_permission: not-set
    user_permission: not-set
    export: true
    mass_update: false
    portal: false
